logging:
  file_name: "/path/to/name"
  level: DEBUG

# アプリケーションの起動設定を行います。
parameters:
  script_file: ""

# 起動するサービスの順番を設定
services:
  - database
  - praqta
  # - http

# praqtaサービス
praqta_service:
  scripts:
    - ./scripts
    - ~/scripts

# HTTPサーバーサービス
http_service:
  host: 0.0.0.0
  port: 8888
  https: yes
  cores: yes
  key_file: "./config/xxx.pem"
  static_root: ./html
  routes:
    "/": index
    "/api/execute": execute_script
    "/api/execute/{script_name}": execute_script
  auth:
    enabled: no
    type: basic
    user: username
    password: XXXXXXXX

# データベースアクセスサービス
database_service:
  default:
    type: sqlite3
    comment: デフォルト接続
    connect: ./data/default.sqlite3
    user:
    password:
    start: always
    auto_commit: true
    init_sqls:
      - ./data/sql/ddl.sql
    pool:
      min: 2
      max: 4
      keep_alive: "select 1"

  postgresql:
    type: postgresql
    comment: PostgreSQLへの接続
    connect: connection
    user: user
    password: password
    init_sqls: []
    auto_commit: true
    start: lazy
    pool:
      min: 2
      max: 4
      keep_alive: "select 1"
