# ログ設定パラメータ
logging:
  filename: "./logs/server.log"
  filemode: w
  format: "%(asctime)s:%(levelname)s:%(message)s"
  datefmt: "%Y/%m/%d %H:%M:%S"
  level: 10 # DEBUG:10/INFO:20

# アプリケーションの起動設定を行います。
parameters:
  script_file: ""

# 起動するサービスの順番を設定
services:
  - database
  - praqta
  # - http

# praqtaサービス
praqta_service:
  scripts:
    - ./scripts
    - ~/scripts

# HTTPサーバーサービス
http_service:
  host: 0.0.0.0
  port: 8888
  ssl: yes
  key_file: "./config/server.pem"
  static_root: ./html
  debug: yes
  auth:
    enabled: no
    type: basic
    user: username
    password: XXXXXXXX

# データベースアクセスサービス(対応DBは、sqlite3/postgresql/mysql/odbc)
database_service:
  default:
    type: sqlite3
    comment: デフォルト接続
    connect: ./data/default.sqlite3
    user:
    password:
    start: always
    auto_commit: true
    init_sqls:
      - ./data/sql/ddl.sql
    pool:
      min: 2
      max: 4
      keep_alive: "select 1"
  #
  # postgresql:
  #   type: postgresql
  #   comment: PostgreSQLへの接続
  #   host: localhost
  #   port: 5432
  #   database: praqta-dev
  #   user: root
  #   password: root2
  #   schema: praqta
  #   init_sqls:
  #     - ./data/sql/pg-ddl.sql
  #   auto_commit: false
  #   start: lazy
  #   pool:
  #     min: 2
  #     max: 4
  #     keep_alive: "select 1"
  #
  # mysql:
  #   type: mysql
  #   comment: MySQLへの接続
  #   host: 127.0.0.1
  #   port: 3306
  #   database: praqta-dev
  #   user: root
  #   password: password
  #   use_unicode: yes
  #   charset: utf8
  #   init_sqls:
  #     - ./data/sql/mysql-ddl.sql
  #   auto_commit: false
  #   start: lazy
  #   pool:
  #     min: 2
  #     max: 4
  #     keep_alive: "select 1"
